-- ETL-3 Knowledge Base schema (dopams_cctns_v2 only).
--
-- public  = application-facing merged/enhanced CCTNS data
-- kb      = internal ETL/enrichment reference data (not application-facing)
--
-- No public-schema copies, aliases, or views for these tables.
-- Source of truth for the data load is a one-time read-only copy from dev-2
-- (see migrate_kb_from_dev2.py). Runtime never connects to dev-2.

CREATE SCHEMA IF NOT EXISTS kb;

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

-- ---------------------------------------------------------------------------
-- kb.drug_categories
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS kb.drug_categories (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_name        TEXT NOT NULL,
    standard_name   TEXT NOT NULL,
    category_group  TEXT NOT NULL,
    is_verified     BOOLEAN DEFAULT true,
    created_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    raw_name_clean  TEXT,
    CONSTRAINT drug_categories_raw_name_key UNIQUE (raw_name)
);

CREATE UNIQUE INDEX IF NOT EXISTS unique_raw_name_clean
    ON kb.drug_categories (raw_name_clean);
CREATE UNIQUE INDEX IF NOT EXISTS unique_raw_name_normalized
    ON kb.drug_categories (lower(TRIM(BOTH FROM raw_name)));
CREATE INDEX IF NOT EXISTS idx_drug_categories_raw_name
    ON kb.drug_categories (raw_name);
CREATE INDEX IF NOT EXISTS idx_drug_categories_standard_name
    ON kb.drug_categories (standard_name);
CREATE INDEX IF NOT EXISTS idx_drug_categories_verified
    ON kb.drug_categories (is_verified);
-- Historical lookup: similarity(raw_name, ?) >= 0.35 AND is_verified = true
CREATE INDEX IF NOT EXISTS trgm_idx_drug_raw_name
    ON kb.drug_categories USING gin (raw_name gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- kb.drug_ignore_list
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS kb.drug_ignore_list (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term        TEXT NOT NULL,
    reason      TEXT,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT drug_ignore_list_term_key UNIQUE (term)
);

CREATE INDEX IF NOT EXISTS idx_drug_ignore_list_term
    ON kb.drug_ignore_list (term);

-- ---------------------------------------------------------------------------
-- kb.geo_reference
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS kb.geo_reference (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_code              VARCHAR,
    state_name              VARCHAR,
    district_code           VARCHAR,
    district_name           VARCHAR,
    sub_district_code       VARCHAR,
    sub_district_name       VARCHAR,
    village_code            VARCHAR,
    village_version         VARCHAR,
    village_name_english    VARCHAR,
    village_name_local      VARCHAR,
    village_category        VARCHAR,
    village_status          VARCHAR,
    created_at              TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS trgm_idx_geo_state
    ON kb.geo_reference USING gin (state_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS trgm_idx_geo_district
    ON kb.geo_reference USING gin (district_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS trgm_idx_geo_sub_district
    ON kb.geo_reference USING gin (sub_district_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS trgm_idx_geo_village
    ON kb.geo_reference USING gin (village_name_english gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- kb.geo_countries
-- Source has no primary key; preserve that shape. timezone kept for fidelity.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS kb.geo_countries (
    country_name    TEXT,
    state_name      TEXT,
    timezone        TEXT
);

CREATE INDEX IF NOT EXISTS idx_geo_countries_country_trgm
    ON kb.geo_countries USING gin (country_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_geo_countries_state_trgm
    ON kb.geo_countries USING gin (state_name gin_trgm_ops);

COMMENT ON SCHEMA kb IS
    'Internal ETL/enrichment knowledge base. Not application-facing.';
COMMENT ON TABLE kb.drug_categories IS
    'Drug name aliases. category_group is KB metadata; enrichment drug_category labels come from rules.resolve_drug_category.';
COMMENT ON TABLE kb.drug_ignore_list IS
    'Exact-match ignore terms applied to resolved primary_drug_name.';
COMMENT ON TABLE kb.geo_reference IS
    'Indian geographic reference for address confirmation.';
COMMENT ON TABLE kb.geo_countries IS
    'Country/state reference for domicile and foreign address confirmation.';
